<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Resultados de Quiniela</title>
<style>
:root{--blue:#075ba8;--dark:#063b72;--pale:#eaf4fd;--line:#dbe6f0}*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#102a43;font-family:system-ui,-apple-system,sans-serif}.page{width:min(1180px,calc(100% - 24px));margin:auto;padding:32px 0}header{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:22px}h1{margin:0;font-size:clamp(1.8rem,4vw,3rem);line-height:1.08}h1 span{color:var(--blue)}.status{color:var(--dark);font-size:.82rem;font-weight:700}.card{overflow:hidden;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:0 16px 45px #1448781f}.toolbar{display:flex;align-items:center;gap:7px;padding:14px;overflow-x:auto;border-bottom:1px solid var(--line)}button{flex:0 0 auto;padding:9px 13px;border:0;border-radius:9px;color:var(--dark);background:var(--pale);font-weight:750;cursor:pointer}button.active{color:#fff;background:var(--blue)}#refresh{margin-left:auto}.table{overflow-x:auto}table{width:100%;min-width:790px;border-collapse:collapse}th,td{padding:11px;border:1px solid var(--line);text-align:center}thead th{color:var(--dark);background:var(--pale)}th:first-child,td:first-child{text-align:left;font-weight:750}.num{display:inline-block;width:85px;padding:10px 5px;border:1.5px solid #bdd4e8;border-radius:10px;color:var(--dark);font-weight:850;letter-spacing:.08em}.empty{color:#a9bdcf}@media(max-width:650px){header{display:block}.status{margin-top:12px}.page{padding-top:22px}}
</style></head><body><main class="page"><header><h1>Resultados del día<br><span id="date">—</span></h1><div class="status" id="status">Cargando…</div></header><section class="card"><div class="toolbar"><button class="active" data-today>Hoy</button><span id="dates" style="display:contents"></span><button id="refresh">Actualizar</button></div><div class="table"><table><thead><tr><th>Provincia</th><th>Previa</th><th>Primera</th><th>Matutina</th><th>Vespertina</th><th>Nocturna</th></tr></thead><tbody id="results"></tbody></table></div></section></main>
<script>
const results=document.querySelector('#results'),date=document.querySelector('#date'),status=document.querySelector('#status'),dates=document.querySelector('#dates');let url='api.php?day=today';
async function load(){status.textContent='Actualizando…';try{const response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.error);date.textContent=data.date_label;results.innerHTML=data.results.map(row=>`<tr><td>${row.jurisdiction}</td>${row.values.map(value=>`<td><span class="num ${value?'':'empty'}">${value||'—'}</span></td>`).join('')}</tr>`).join('');status.textContent=data.is_history?'Resultado histórico':'Datos actualizados'}catch(error){status.textContent=error.message}}
function activate(button){document.querySelectorAll('.toolbar button').forEach(item=>item.classList.toggle('active',item===button))}document.querySelector('[data-today]').onclick=e=>{url='api.php?day=today';activate(e.target);load()};document.querySelector('#refresh').onclick=load;
fetch('api.php?day=dates').then(r=>r.json()).then(data=>{data.dates.forEach((label,index)=>dates.insertAdjacentHTML('beforeend',`<button data-index="${index}">${label}</button>`));document.querySelectorAll('[data-index]').forEach(button=>button.onclick=()=>{url=`api.php?day=history&index=${button.dataset.index}`;activate(button);load()})});load();setInterval(load,300000);
</script></body></html>

